// frontend/packages/enduser-frontend/src/components/common/file-upload.vue
<!--
SPDX-FileCopyrightText: 2017-2020 City of Espoo

SPDX-License-Identifier: LGPL-2.1-or-later
-->

<template>
  <div class="file-upload-container" v-on:drop.prevent v-on:dragover.prevent>
    <label class="file-input-label" v-on:drop="onDrop">
      <input
        type="file"
        accept="image/jpeg, image/png, application/pdf, application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document, application/vnd.oasis.opendocument.text"
        @change="onChange"
        data-qa="btn-upload-file"
      />
      <h4>{{ $t('file-upload.input.title') }}</h4>
      <span
        v-for="text in $t('file-upload.input.text')"
        v-bind:key="text"
        v-text="text"
      />
    </label>
    <div class="spacer" />
    <div class="files" data-qa="files">
      <div
        v-bind:class="{ uploaded: !inProgress(file) && !file.error }"
        class="file"
        v-for="file in files"
        v-bind:key="file.key"
      >
        <div class="file-icon-container">
          <font-awesome-icon
            :icon="['fal', fileIcon(file)]"
            size="lg"
          ></font-awesome-icon>
        </div>
        <div class="file-details">
          <div class="file-header">
            <a
              v-if="file.id"
              class="file-name"
              @click="deliverBlob(file)"
              target="_blank"
              rel="noreferrer"
            >
              {{ file.name }}
            </a>
            <span v-else class="file-name">{{ file.name }}</span>
            <div>
              <button
                class="file-header-icon-button"
                @click="retryFile(file)"
                v-if="fileUploadFailed(file)"
              >
                <font-awesome-icon
                  :icon="['fal', 'redo']"
                  size="2x"
                ></font-awesome-icon>
              </button>
              <button
                class="file-header-icon-button"
                @click="deleteFile(file)"
                :disabled="inProgress(file) && !file.error"
                v-bind:data-qa="deleteButtonDataQa(file)"
              >
                <font-awesome-icon
                  :icon="['fal', 'times']"
                  size="2x"
                ></font-awesome-icon>
              </button>
            </div>
          </div>
          <transition name="progress-bar">
            <div class="file-progress-bar" v-show="inProgress(file)">
              <div class="file-progress-bar-background">
                <div
                  :class="[
                    'file-progress-bar-progress',
                    { error: !!file.error }
                  ]"
                  :style="progressBarStyles(file)"
                />
              </div>
              <div class="file-progress-bar-error" v-if="file.error">
                <span>{{ errorMessage(file) }}</span>
                <font-awesome-icon
                  :icon="['fas', 'exclamation-triangle']"
                  size="1x"
                ></font-awesome-icon>
              </div>
              <div class="file-progress-bar-details" v-else>
                <span>{{
                  inProgress(file)
                    ? $t('file-upload.loading')
                    : $t('file-upload.loaded')
                }}</span>
                <span>{{ file.progress }} %</span>
              </div>
            </div>
          </transition>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
  import axios from 'axios'
  export default {
    props: {
      files: Array,
      onUpload: Function,
      onDelete: Function
    },
    methods: {
      deliverBlob(file) {
        axios({
          url: `/api/application/attachments/${file.id}/download`,
          method: 'GET',
          responseType: 'blob',
        }).then((response) => {
          const url = window.URL.createObjectURL(new Blob([response.data]))
          const link = document.createElement('a')
          link.href = url
          link.setAttribute('download', `${file.name}`)
          document.body.appendChild(link)
          link.click()
          link.remove()
        })
      },
      onChange(event) {
        this.onUpload(event.target.files[0])
      },
      onDrop(event) {
        if (event.dataTransfer.files && event.dataTransfer.files[0]) {
          this.onUpload(event.dataTransfer.files[0])
        }
      },
      deleteFile(file) {
        this.onDelete(file)
      },
      retryFile(file) {
        this.onDelete(file)
        this.onUpload(file.file)
      },
      fileIcon(file) {
        switch (file.contentType) {
          case 'image/jpeg':
          case 'image/png':
            return 'file-image'
          case 'application/pdf':
            return 'file-pdf'
          case 'application/msword':
          case 'application/vnd.openxmlformats-officedocument.wordprocessingml.document':
          case 'application/vnd.oasis.opendocument.text':
            return 'file-word'
          default:
            return 'file'
        }
      },
      inProgress(file) {
        return !file.id
      },
      progressBarStyles(file) {
        return `width: ${file.progress}%;`
      },
      errorMessage(file) {
        const messages = this.$t('file-upload.error')
        return messages[file.error] || messages.default
      },
      fileUploadFailed(file) {
        return file.error === 'server-error'
      },
      deleteButtonDataQa(file) {
        return `btn-delete-file-${file.name}`
      }
    }
  }
</script>

<style lang="scss">
  $progress-bar-height: 3px;
  $progress-bar-border-radius: 1px;

  .file-upload-container {
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    align-items: flex-start;

    .file-input-label {
      display: flex;
      flex-direction: column;
      justify-content: center;
      background: $white-bis;
      border: 1px dashed $grey;
      border-radius: 8px;
      width: min(500px, 70vw);
      padding: 24px;
      text-align: center;

      input {
        display: none;
      }

      h4 {
        font-size: 18px;
        margin-bottom: 14px;
      }

      span {
        font-size: 13px;
      }
    }

    .spacer {
      padding: 20px;
    }

    .files {
      display: flex;
      flex-direction: column;

      > *:not(:last-child) {
        margin-bottom: 20px;
      }

      .file {
        display: flex;
        flex-direction: row;
        flex-wrap: nowrap;
        color: $grey-dark;

        .file-icon-container {
          margin-right: 16px;
          flex: 0;
        }

        .file-details {
          flex: 1;
          display: flex;
          flex-direction: column;
          flex-wrap: nowrap;

          .file-header {
            display: flex;
            flex-direction: row;
            flex-wrap: nowrap;
            justify-content: space-between;
            font-size: 15px;

            .file-header-icon-button {
              border: none;
              background: none;
              padding: 4px;
              margin-left: 12px;
              color: $grey;
              cursor: pointer;

              &:hover {
                color: $blue;
              }

              &:disabled {
                color: $grey-light;
                cursor: not-allowed;
              }
            }

            .file-name {
              width: min(400px, 50vw);
              white-space: nowrap;
              overflow: hidden;
              text-overflow: ellipsis;
            }
          }

          .file-progress-bar {
            margin-top: 16px;
            font-size: 14px;

            > *:not(:last-child) {
              margin-bottom: 4px;
            }

            .file-progress-bar-background {
              position: relative;
              background: $grey;
              height: $progress-bar-height;
              border-radius: $progress-bar-border-radius;

              .file-progress-bar-progress {
                position: absolute;
                top: 0;
                left: 0;
                background: $blue;
                height: $progress-bar-height;
                border-radius: $progress-bar-border-radius;
                transition: width 0.5s ease-out;

                &.error {
                  background: $orange;
                }
              }
            }

            .file-progress-bar-details {
              display: flex;
              flex-direction: row;
              justify-content: space-between;
              color: $grey-dark;
            }

            .file-progress-bar-error {
              color: darken($orange, 10);

              svg {
                color: $orange;
                margin-left: 8px;
              }
            }
          }

          .progress-bar-leave-active {
            transition: opacity 0s ease-in 2s;
          }

          .progress-bar-leave-to {
            opacity: 0;
          }
        }
      }
    }
  }
</style>

// frontend/packages/citizen-frontend/src/applications/editor/FileUpload.tsx
// SPDX-FileCopyrightText: 2017-2021 City of Espoo
//
// SPDX-License-Identifier: LGPL-2.1-or-later

import React, { useState } from 'react'
import styled from 'styled-components'
import { useTranslation } from '~localization'
import { Gap } from '@evaka/lib-components/src/white-space'
import colors from '@evaka/lib-components/src/colors'
import IconButton from '@evaka/lib-components/src/atoms/buttons/IconButton'
import {
  faExclamationTriangle,
  faFile,
  faFileImage,
  faFilePdf,
  faFileWord,
  faInfo,
  faTimes
} from '@evaka/lib-icons'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { UUID } from '@evaka/lib-common/src/types'
import { Result } from '@evaka/lib-common/src/api'
import {
  ApplicationAttachment,
  FileObject
} from '@evaka/lib-common/src/api-types/application/ApplicationDetails'
import { IconDefinition } from '@fortawesome/fontawesome-svg-core'
import InfoModal from '@evaka/lib-components/src/molecules/modals/InfoModal'
import { getFileAvailability, getFileBlob } from '~applications/api'

export type FileUploadProps = {
  files: ApplicationAttachment[]
  onUpload: (
    file: File,
    onUploadProgress: (progressEvent: ProgressEvent) => void
  ) => Promise<Result<UUID>>
  onDelete: (id: UUID) => Promise<Result<void>>
}

const FileUploadContainer = styled.div`
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;
  align-items: flex-start;
`

const FileInputLabel = styled.label`
  display: flex;
  flex-direction: column;
  justify-content: center;
  background: ${colors.greyscale.lightest};
  border: 1px dashed ${colors.greyscale.medium};
  border-radius: 8px;
  width: min(500px, 70vw);
  padding: 24px;
  text-align: center;

  & input {
    display: none;
  }

  & h4 {
    font-size: 18px;
    margin-bottom: 14px;
  }
`

const Icon = styled(FontAwesomeIcon)`
  height: 1rem !important;
  width: 1rem !important;
  margin-right: 10px;
`

const UploadedFiles = styled.div`
  display: flex;
  flex-direction: column;
  font-size: 15px;
  margin-top: 5px;

  > *:not(:last-child) {
    margin-bottom: 20px;
  }
`

const File = styled.div`
  display: flex;
  flex-direction: row;
  flex-wrap: nowrap;
  color: ${colors.greyscale.dark};
`

const FileIcon = styled(FontAwesomeIcon)`
  margin-right: 16px;
  font-size: 20px;
  flex: 0;
  color: ${colors.blues.primary};
`

const FileDetails = styled.div`
  flex: 1;
  display: flex;
  flex-direction: column;
  flex-wrap: nowrap;
`

const FileHeader = styled.div`
  display: flex;
  flex-direction: row;
  flex-wrap: nowrap;
  justify-content: space-between;
  text-align: left;
`

const ProgressBarContainer = styled.div`
  position: relative;
  background: ${colors.greyscale.medium};
  height: 3px;
  border-radius: 1px;
`

interface ProgressBarProps {
  progress: number
}

const ProgressBar = styled.div<ProgressBarProps>`
  width: ${(props) => props.progress}%;
  position: absolute;
  top: 0;
  left: 0;
  background: ${colors.blues.medium};
  height: 3px;
  border-radius: 1px;
  transition: width 0.5s ease-out;
  margin-bottom: 3px;
`
const FileDownloadButton = styled.button`
  border: none;
  background: none;
  color: ${colors.blues.primary};
  cursor: pointer;
  font-size: 15px;
`

const FileDeleteButton = styled(IconButton)`
  border: none;
  background: none;
  padding: 4px;
  margin-left: 12px;
  color: ${colors.greyscale.medium};

  &:hover {
    color: ${colors.blues.medium};
  }

  &:disabled {
    color: ${colors.greyscale.lighter};
    cursor: not-allowed;
  }
`

const ProgressBarDetails = styled.div`
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  color: ${colors.greyscale.dark};
`

const ProgressBarError = styled.div`
  color: ${colors.accents.orangeDark};
  margin-top: 3px;
  svg {
    color: ${colors.accents.orange};
    margin-left: 8px;
  }
`

const attachmentToFile = (attachment: ApplicationAttachment): FileObject => {
  return {
    id: attachment.id,
    file: undefined,
    key: Math.random(),
    name: attachment.name,
    contentType: attachment.contentType,
    progress: 100,
    error: undefined
  }
}

const fileIcon = (file: FileObject): IconDefinition => {
  switch (file.contentType) {
    case 'image/jpeg':
    case 'image/png':
      return faFileImage
    case 'application/pdf':
      return faFilePdf
    case 'application/msword':
    case 'application/vnd.openxmlformats-officedocument.wordprocessingml.document':
    case 'application/vnd.oasis.opendocument.text':
      return faFileWord
    default:
      return faFile
  }
}

const inProgress = (file: FileObject): boolean => file.progress !== 100

export default React.memo(function FileUpload({
  files,
  onUpload,
  onDelete
}: FileUploadProps) {
  const t = useTranslation()

  const [modalVisible, setModalVisible] = useState<boolean>(false)

  const [uploadedFiles, setUploadedFiles] = useState<FileObject[]>(
    files.map(attachmentToFile)
  )

  const onChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    if (event.target.files && event.target.files.length > 0) {
      void addAttachment(event.target.files[0], onUpload)
      if (event.target.value) event.target.value = ''
    }
  }

  const onDrop = (event: React.DragEvent<HTMLLabelElement>) => {
    if (event.dataTransfer && event.dataTransfer.files[0]) {
      void addAttachment(event.dataTransfer.files[0], onUpload)
    }
  }

  const errorMessage = ({ error }: FileObject) => {
    const messages = t.fileUpload.error
    return error && messages[error]
  }

  const deleteFile = async (file: FileObject) => {
    try {
      if (!file.error) await onDelete(file.id)
      setUploadedFiles((old: FileObject[]) => {
        return old.filter((item) => item.id !== file.id)
      })
    } catch (e) {
      console.error(e)
    }
  }

  const getFileIfAvailable = async (file: FileObject) => {
    const result = await getFileAvailability(file)
    if (result.isSuccess) {
      result.value.fileAvailable
        ? void deliverBlob(file)
        : setModalVisible(true)
    }
  }

  const deliverBlob = async (file: FileObject) => {
    const result = await getFileBlob(file)
    if (result.isSuccess) {
      const url = URL.createObjectURL(new Blob([result.value]))
      const link = document.createElement('a')
      link.href = url
      link.target = '_blank'
      link.setAttribute('download', `${file.name}`)
      link.rel = 'noreferrer'
      document.body.appendChild(link)
      link.click()
      link.remove()
    }
  }

  const updateUploadedFile = (
    file: FileObject,
    id: UUID | undefined = undefined
  ) =>
    setUploadedFiles((old) => {
      const others = old.filter((item) => item.id !== (id ?? file.id))
      return [...others, file]
    })

  const addAttachment = async (
    file: File,
    onUpload: (
      file: File,
      onUploadProgress: (progressEvent: ProgressEvent) => void
    ) => Promise<Result<UUID>>
  ) => {
    const error = file.size > 10000000 ? 'FILE_TOO_LARGE' : undefined
    const pseudoId = Math.random()
    const fileObject: FileObject = {
      id: pseudoId.toString(),
      key: pseudoId,
      file,
      name: file.name,
      contentType: file.type,
      progress: 0,
      error
    }

    updateUploadedFile(fileObject)

    if (error) {
      return
    }

    const updateProgress = ({ loaded, total }: ProgressEvent) => {
      const progress = Math.round((loaded / total) * 100)
      updateUploadedFile({ ...fileObject, progress })
    }

    try {
      const result = await onUpload(file, updateProgress)
      if (result.isFailure) throw new Error(result.message)
      if (result.isSuccess)
        updateUploadedFile(
          {
            ...fileObject,
            progress: 100,
            id: result.value
          },
          fileObject.id
        )
    } catch (e) {
      updateUploadedFile({ ...fileObject, error: 'SERVER_ERROR' })
    }
  }

  return (
    <FileUploadContainer>
      {modalVisible && (
        <InfoModal
          title={t.fileUpload.modalHeader}
          text={t.fileUpload.modalMessage}
          close={() => setModalVisible(false)}
          icon={faInfo}
        />
      )}
      <FileInputLabel className="file-input-label" onDrop={onDrop}>
        <input
          type="file"
          accept="image/jpeg, image/png, application/pdf, application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document, application/vnd.oasis.opendocument.text"
          onChange={onChange}
          data-qa="btn-upload-file"
        />
        <h4>{t.fileUpload.input.title}</h4>
        <p>{t.fileUpload.input.text.join('\n')}</p>
      </FileInputLabel>
      <Gap horizontal size={'s'} />
      <UploadedFiles>
        {uploadedFiles.map((file) => (
          <File key={file.key}>
            <FileIcon icon={fileIcon(file)} />
            <FileDetails>
              <FileHeader>
                {!file.error ? (
                  <FileDownloadButton onClick={() => getFileIfAvailable(file)}>
                    {file.name}
                  </FileDownloadButton>
                ) : (
                  <span>{file.name}</span>
                )}
                <FileDeleteButton
                  icon={faTimes}
                  onClick={() => deleteFile(file)}
                />
              </FileHeader>
              {inProgress(file) && (
                <ProgressBarContainer>
                  <ProgressBar progress={file.progress} />
                  {file.error && (
                    <ProgressBarError>
                      <span>{errorMessage(file)}</span>
                      <Icon icon={faExclamationTriangle} />
                    </ProgressBarError>
                  )}
                  {!file.error && (
                    <ProgressBarDetails>
                      <span>
                        {inProgress(file)
                          ? t.fileUpload.loading
                          : t.fileUpload.loaded}
                      </span>
                      <span>{file.progress} %</span>
                    </ProgressBarDetails>
                  )}
                </ProgressBarContainer>
              )}
            </FileDetails>
          </File>
        ))}
      </UploadedFiles>
    </FileUploadContainer>
  )
})
