// frontend/packages/enduser-frontend/src/components/common/footer-component.vue
<!--
SPDX-FileCopyrightText: 2017-2020 City of Espoo

SPDX-License-Identifier: LGPL-2.1-or-later
-->

<template>
  <footer class="common-footer">
    <div>&copy; {{ $t('footer.espoo-label') }}</div>
    <div>
      <a
        :href="$t('footer.privacy-policy-link')"
        target="_blank"
        rel="noreferrer"
      >
        {{ $t('footer.privacy-policy-label') }}
      </a>
    </div>
    <div>
      <a
        :href="$t('footer.send-feedback-link')"
        target="_blank"
        rel="noreferrer"
      >
        {{ $t('footer.send-feedback-label') }}
      </a>
    </div>
  </footer>
</template>

<script>
  export default {
    name: 'footer-component'
  }
</script>

<style lang="scss">
  .common-footer {
    display: flex;
    flex-direction: row;
    justify-content: center;
    font-size: $size-small;
    a {
      color: $link;
    }
    div {
      display: inline-block;
      margin: 0 10px 0 10px;
    }
  }

  .map-footer {
    div {
      margin-left: 5px;
    }
  }

  @media screen and (min-width: 768px) {
    .map-footer {
      display: block;
    }
  }

  .space-footer {
    padding: 20px 0 20px 0;
  }
</style>

// frontend/src/employee-frontend/components/Footer.tsx
// SPDX-FileCopyrightText: 2017-2022 City of Espoo
//
// SPDX-License-Identifier: LGPL-2.1-or-later

import React from 'react'
import styled from 'styled-components'
import { EvakaLogo } from 'lib-components/atoms/EvakaLogo'
import Container from 'lib-components/layout/Container'
import { defaultMargins } from 'lib-components/white-space'
import { colors } from 'lib-customizations/common'
import { cityLogo } from 'lib-customizations/employee'
import { useTranslation } from '../state/i18n'

export const footerHeight = '120px'

const FooterContainer = styled.div`
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin: ${defaultMargins.s} 0;
  height: ${footerHeight};

  svg,
  img {
    max-width: 200px;
    width: auto;
    max-height: 100%;
  }
`

const Content = styled.div`
  display: flex;
  gap: ${defaultMargins.XL};
`

export const Footer = React.memo(function Footer() {
  const { i18n } = useTranslation()
  return (
    <footer>
      <Container>
        <FooterContainer>
          {'src' in cityLogo ? (
            <img
              src={cityLogo.src}
              alt={cityLogo.alt}
              data-qa="footer-city-logo"
            />
          ) : (
            cityLogo
          )}
          <Content>
            <span data-qa="footer-city-label">
              &copy; {i18n.footer.cityLabel}
            </span>
            <a href={i18n.footer.linkHref} data-qa="footer-city-link">
              {i18n.footer.linkLabel}
            </a>
          </Content>
          <EvakaLogo color={colors.main.m1} />
        </FooterContainer>
      </Container>
    </footer>
  )
})
