// frontend/packages/enduser-frontend/src/components/common/footer-component.vue
<!--
SPDX-FileCopyrightText: 2017-2020 City of Espoo

SPDX-License-Identifier: LGPL-2.1-or-later
-->

<template>
  <footer class="common-footer">
    <div>&copy; {{ $t('footer.espoo-label') }}</div>
    <div>
      <a
        :href="$t('footer.privacy-policy-link')"
        target="_blank"
        rel="noreferrer"
      >
        {{ $t('footer.privacy-policy-label') }}
      </a>
    </div>
    <div>
      <a
        :href="$t('footer.send-feedback-link')"
        target="_blank"
        rel="noreferrer"
      >
        {{ $t('footer.send-feedback-label') }}
      </a>
    </div>
  </footer>
</template>

<script>
  export default {
    name: 'footer-component'
  }
</script>

<style lang="scss">
  .common-footer {
    display: flex;
    flex-direction: row;
    justify-content: center;
    font-size: $size-small;
    a {
      color: $link;
    }
    div {
      display: inline-block;
      margin: 0 10px 0 10px;
    }
  }

  .map-footer {
    div {
      margin-left: 5px;
    }
  }

  @media screen and (min-width: 768px) {
    .map-footer {
      display: block;
    }
  }

  .space-footer {
    padding: 20px 0 20px 0;
  }
</style>

// frontend/packages/citizen-frontend/src/Footer.tsx
// SPDX-FileCopyrightText: 2017-2021 City of Espoo
//
// SPDX-License-Identifier: LGPL-2.1-or-later

import React from 'react'
import { useTranslation } from '~localization'
import styled from 'styled-components'
import colors from '@evaka/lib-components/src/colors'

export default React.memo(function Footer() {
  const t = useTranslation()
  return (
    <FooterContainer>
      <FooterItem>{t.footer.espooLabel}</FooterItem>
      <FooterItem>
        <FooterLink href={t.footer.privacyPolicyLink} data-qa={'nav-old-map'}>
          {t.footer.privacyPolicy}
        </FooterLink>
      </FooterItem>
      <FooterItem>
        <FooterLink href={t.footer.sendFeedbackLink} data-qa={'nav-old-map'}>
          {t.footer.sendFeedback}
        </FooterLink>
      </FooterItem>
    </FooterContainer>
  )
})

const FooterContainer = styled.footer`
  display: flex;
  flex-direction: row;
  justify-content: center;
  flex-wrap: wrap;
  padding: 20px 0 20px 0;
  font-size: 12px;
  font-weight: 400;
`

const FooterItem = styled.div`
  display: inline-block;
  margin: 0 40px 0 40px;
`

const FooterLink = styled.a`
  color: ${colors.brandEspoo.espooBlue};
  text-decoration: none;
`
